# Generated by Django 3.1.2 on 2020-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('price', models.CharField(max_length=30, verbose_name='цена')),
            ],
        ),
    ]
