# Generated by Django 3.1.2 on 2020-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripecheckout', '0002_auto_20201017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=25, verbose_name='Цена'),
        ),
    ]
