# Generated by Django 3.1.2 on 2020-10-17 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripecheckout', '0003_auto_20201017_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(max_length=25, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=25, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена'),
        ),
    ]
