# Generated by Django 3.1.2 on 2020-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripecheckout', '0004_auto_20201017_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'Доллары'), ('rub', 'Рубли')], default='usd', max_length=10, verbose_name='Валюта товара'),
        ),
    ]
